advanced/frontend/models/Book.php
<?php

namespace frontend\models;

use Yii;
use yii\behaviors\TimestampBehavior;
use yii\web\UploadedFile;
use yii\imagine\Image;

/**
 * This is the model class for table "book".
 *
 * @property integer $id
 * @property string $name
 * @property integer $created_at
 * @property integer $updated_at
 * @property string $preview
 * @property string $date
 * @property integer $author_id
 */
class Book extends \yii\db\ActiveRecord
{
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'book';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'date', 'author_id'], 'required'],
            [['created_at', 'updated_at', 'author_id'], 'integer'],
            [['date'], 'safe'],
            [['name'], 'string', 'max' => 255],
            [['preview'], 'safe'],
            [['preview'], 'file', 'skipOnEmpty' => true, 'extensions' => 'png, jpg, jpeg']
        ];
    }

    public function attributes() {
        $attributes = parent::attributes();
        return array_merge($attributes, [
            'date_from',
            'date_till'
        ]);
    }
    
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'created_at' => 'Дата добавления',
            'updated_at' => 'Дата редактирования',
            'preview' => 'Превью',
            'date' => 'Дата выхода книги',
            'author_id' => 'Автор',
        ];
    }
    
    public function getAuthor()
    {
        return $this->hasMany(Author::className(), ['id' => 'author_id']);
    }
    
    public function upload()
    {
        if ($this->validate()) {
            //$this->preview->saveAs('uploads/' . $this->preview->baseName . '.' . $this->preview->extension);
            $filename = 'uploads/book_'.$this->id.'.jpg';
            $thumb = 'uploads/book_'.$this->id.'_100.jpg';
                //Yii::$app->db->createCommand("UPDATE user SET `avatar`='$filename' WHERE id=:id") ->bindValue(':id', $userID) ->execute();
                //$filename = 'uploads/avatar/'.$dir.'/user_'.$userID.'_avatar_' . Yii::$app->security->generateRandomString() . '.jpg';
                if (isset($this->preview->tempName)) {
                    Image::thumbnail($this->preview->tempName, 800, 600)->save($filename, ['quality' => 100]);
                    Image::thumbnail($this->preview->tempName, 100, 70)->save($thumb, ['quality' => 100]);
                }
            $this->preview = isset($this->preview->tempName) ? $filename : null;
            return true;
        } else {
            $this->preview = null;
            return false;
        }
    }
}

advanced/frontend/controllers/AuthorController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\Author;
use frontend\models\AuthorSearch;
use frontend\models\Book;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

/**
 * AuthorController implements the CRUD actions for Author model.
 */
class AuthorController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index', 'view', 'create', 'update', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Author models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AuthorSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Author model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Author model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Author();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Author model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Author model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $books = Book::find()->where(['author_id' => $id])->count();
        if ($books >= 1) {
            \Yii::$app->getSession()->setFlash('error', 'Вы не можете удалить этого автора, так как не удалены книги этого автора.');
        } else {
            \Yii::$app->getSession()->setFlash('success', 'Автор успешно удален.');
            $this->findModel($id)->delete();
        }

        return $this->redirect(['index']);
    }

    /**
     * Finds the Author model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Author the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Author::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

advanced/frontend/controllers/BookController.php
<?php

namespace frontend\controllers;

use Yii;
use frontend\models\Book;
use frontend\models\BookSearch;
use frontend\models\Author;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\UploadedFile;
use yii\filters\VerbFilter;

use yii\helpers\ArrayHelper;
use yii\helpers\Url;

/**
 * BookController implements the CRUD actions for Book model.
 */
class BookController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index', 'view', 'create', 'update', 'delete'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Lists all Book models.
     * @return mixed
     */
    public function actionIndex()
    {
        Url::remember();
        $searchModel = new BookSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $dataProvider->pagination->pageSize = 5;
        
        $authorList = ArrayHelper::map(
            Author::find()->orderBy(['firstname' => SORT_ASC,])->all(),
            'id', function($model, $defaultValue) {
                return $model->firstname.' '.$model->lastname;
            }
        );
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'authorList' => $authorList,
        ]);
    }

    /**
     * Displays a single Book model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Book model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $authorList = ArrayHelper::map(
            Author::find()->orderBy(['firstname' => SORT_ASC,])->all(),
            'id', function($author, $defaultValue) {
                return $author->firstname.' '.$author->lastname;
            }
        );
        
        $model = new Book();
        
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $model->preview = UploadedFile::getInstance($model, 'preview');
            if ($model->upload()) {
                $model->save();
            }
            \Yii::$app->getSession()->setFlash('success', 'Книга успешно добавлена в библиотеку.');
            //return $this->redirect(['view', 'id' => $model->id]);
            return $this->redirect(['index']);
        } else {
            return $this->render('create', [
                'model' => $model,
                'authorList' => $authorList,
            ]);
        }
    }

    /**
     * Updates an existing Book model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $authorList = ArrayHelper::map(
            Author::find()->orderBy(['firstname' => SORT_ASC,])->all(),
            'id', function($author, $defaultValue) {
                return $author->firstname.' '.$author->lastname;
            }
        );
        
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            $model->preview = UploadedFile::getInstance($model, 'preview');
            if ($model->upload()) {
                $model->save();
            }
            \Yii::$app->getSession()->setFlash('success', 'Книга успешно отредактирована.');
            //return $this->redirect(['view', 'id' => $model->id]);
            return $this->redirect([Url::previous()]);
        } else {
            return $this->render('update', [
                'model' => $model,
                'authorList' => $authorList,
            ]);
        }
    }

    /**
     * Deletes an existing Book model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);

        if(is_file($model->preview)) {
            unlink($model->preview);
        }
        if(is_file('uploads/book_'.$model->id.'_100.jpg')) {
            unlink('uploads/book_'.$model->id.'_100.jpg');
        }
        
        if ($model->delete()) {
            \Yii::$app->getSession()->setFlash('success', 'Книга успешно удалена.');
        }

        return $this->redirect(['index']);
    }

    /**
     * Finds the Book model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Book the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Book::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

advanced/frontend/views/book/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\jui\DatePicker;

/* @var $this yii\web\View */
/* @var $model frontend\models\Book */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="book-form">

    <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

    <div class="row">
        <div class="col-md-6">
            <?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
        </div>
        <div class="col-md-6">
            <label>Дата выхода книги</label><br /> <?= DatePicker::widget([
                'model' => $model,
                'attribute' => 'date',
                'language' => 'ru',
                'dateFormat' => 'yyyy-MM-dd',
            ]); ?>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-6">
            <?= Html::activeDropDownList($model, 'author_id', $authorList, [
                'prompt' => 'Автор',
                'class' => 'form-control'
            ]) ?>
        </div>
    </div>
    
    <br />
    <div class="form-group">
        <?= $form->field($model, 'preview')->fileInput() ?>
        
        <?= is_file('uploads/book_'.$model->id.'_100.jpg') ? Html::img('/uploads/book_'.$model->id.'_100.jpg') : ''; ?>
    </div>
    
    <?= $form->errorSummary($model); ?>
    
    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Добавить' : 'Сохранить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

advanced/frontend/views/book/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\jui\DatePicker;

/* @var $this yii\web\View */
/* @var $model frontend\\models\BookSearch */
/* @var $form yii\widgets\ActiveForm */
if (isset($model->date_from) && $model->date_from) {
    $model->date_from = \DateTime::createFromFormat('d/m/Y', $model->date_from)->format('Y-m-d');
}
if (isset($model->date_till) && $model->date_till) {
    $model->date_till = \DateTime::createFromFormat('d/m/Y', $model->date_till)->format('Y-m-d');
}
?>

<div class="book-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <div class="row">
        <div class="col-md-3">
            <?= Html::activeDropDownList($model, 'author_id', $authorList, [
                'prompt' => 'Автор',
                'class' => 'form-control'
            ]) ?>
        </div>
        <div class="col-md-3">
            <?= $form->field($model, 'name', [
                'inputOptions' => [
                    'class'=>'form-control',
                    'placeholder'=>'Название книги'
                ]
            ])->label(false) ?>
        </div>
    </div>
    
    <div class="row">
        <div class="col-md-10">
            Дата выхода книги: 
            <?= DatePicker::widget([
                'model' => $model,
                'attribute' => 'date_from',
                'language' => 'ru',
                'dateFormat' => 'dd/MM/yyyy',
            ]); ?>
            до 
            <?= DatePicker::widget([
                'model' => $model,
                'attribute' => 'date_till',
                'language' => 'ru',
                'dateFormat' => 'dd/MM/yyyy',
            ]); ?>
        </div>
        <div class="col-md-2">
            <?= Html::submitButton('Искать', ['class' => 'btn btn-primary']) ?>
            <?php // echo Html::resetButton('Сбросить', ['class' => 'btn btn-default']) ?>
        </div>
    </div> 

    <?php ActiveForm::end(); ?>

</div>

advanced/frontend/views/book/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model frontend\models\Book */

$this->title = 'Добавление книги';
$this->params['breadcrumbs'][] = ['label' => 'Книги', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="book-create">

    <h1><?= Html::encode($this->title) ?></h1>
    <hr />

    <?= $this->render('_form', [
        'model' => $model,
        'authorList' => $authorList,
    ]) ?>

</div>

advanced/frontend/views/book/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel frontend\\models\BookSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Книги';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="book-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <hr />
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?= Html::a('Добавить книгу', ['create'], ['class' => 'btn btn-success']) ?>
        <?= Html::a('Добавить автора', ['/author/create'], ['class' => 'btn btn-success']) ?>
    </p>

    <hr />
    
    <?php echo $this->render('_search', ['model' => $searchModel, 'authorList' => $authorList]); ?>
    
    <hr />
    
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        //'filterModel' => $searchModel,
        'columns' => [
            //['class' => 'yii\grid\SerialColumn'],

            'id',
            'name',
            [
                'attribute' => 'preview',
                'value' => function ($data) {
                    if (is_file($data->preview)) {
                        return '<a class="fancybox" href="/'.$data->preview.'?date='.$data->updated_at.'" data-fancybox-group="gallery" title=" '.$data->name.'
Автор: '.$data->author[0]->firstname.' '.$data->author[0]->lastname.'  ">
				<img  src="/uploads/book_'.$data->id.'_100.jpg?date='.$data->updated_at.'" alt="" />
			</a>';
                    }
                },
                'format' => 'raw'
            ],
            [
                'attribute' => 'author_id',
                'label' => 'Автор',
                'value' => function ($data) {
                    return $data->author[0]->firstname.' '.$data->author[0]->lastname;
                },
                'format' => 'raw'
            ],
            'date:date',
            'created_at:relativetime',
            //'updated_at',

            ['class' => 'yii\grid\ActionColumn', 'template'=>'{update}{view}{delete}',
                'header' => 'Кнопки действий',
                'buttons' => [
                    'update' => function ($url, $model) {     
                        return Html::a('[ред.]', $url, [
                            'title' => 'Редактировать',
                            'target' => '_blank',
                        ]);                                
                    },
                    'view' => function ($url, $model) {     
                        return Html::a('[просм.]', $url, [
                            'title' => 'Просмотр '.$model->name,
                            'class' => 'various fancybox.ajax'
                        ]);                                
                    },
                    'delete' => function ($url, $model) {     
                        return Html::a('[удал.]', $url, [
                            'title' => 'Удалить '.$model->name,
                            'data-method' => 'post',
                            'data-confirm' => 'Вы уверены, что хотите удалить эту книгу?'
                        ]);                                
                    },
                ]
            ],
        ],
    ]); ?>

</div>

advanced/frontend/views/book/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model frontend\models\Book */

$this->title = 'Редактирование кники: ' . ' ' . $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Книги', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->name, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Редактирование';
?>
<div class="book-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
        'authorList' => $authorList,
    ]) ?>

</div>

advanced/frontend/views/book/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model frontend\models\Book */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => 'Книги', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="book-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Редактировать', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Удалить', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Вы уверены, что хотите удалить книгу '.$model->name.'?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'name',
            'author_id',
            'created_at:datetime',
            'updated_at:relativetime',
            [
                'label'  => 'Превью',
                'format' => 'raw',
                'value'  => is_file('uploads/book_'.$model->id.'_100.jpg') ? Html::img('/uploads/book_'.$model->id.'_100.jpg') : '',
            ],
            'date',
            
        ],
    ]) ?>

</div>